version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"  # Changed to match the default port Laravel uses
    depends_on:
      - db
    networks:
      - laravel-net
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: php artisan serve --host=0.0.0.0 --port=8000  # Explicit command to start Laravel server

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3307:3306"  # Expose MySQL on port 3307 of the host
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  dbdata:

networks:
  laravel-net:

